name: GitActions - Basic
run-name: Running ${{ github.event_name }}
on:
  push:
    #branches:
      # - main
     # - develop
    branches-ignore:
      - main
    paths:
      - '**.txt'
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comment only
        run: | 
          echo "Comment my basic push on ${{ runner.os }}."
